/**
 * Row shapes for our tables.
 *
 * Hand-written rather than generated by the Supabase CLI, which needs a linked
 * project and a login — that would put a credential step between cloning this
 * repo and building it. The schema is small and lives beside these types in
 * `supabase/migrations/0001_init.sql`; keep the two in step.
 *
 * Note these are *row* types, not a `Database` generic for the client. Chasing
 * the exact generic shape supabase-js expects is a moving target across minor
 * versions, and it buys little here: every row crosses into application types
 * through an explicit mapper in `src/lib/sync/mapping.ts`, which is where the
 * real checking happens.
 */

import type {
  Cadence,
  CheckInRhythm,
  DomainId,
  MotivationStyle,
  QuestKind,
  QuestWindow,
} from "@/lib/types";

export type AccountStatus =
  | "trialing"
  | "active"
  | "past_due"
  | "expired"
  | "comped";

export type AccountRole = "player" | "staff" | "admin";

export interface ProfileRow {
  id: string;
  display_name: string;
  priorities: DomainId[];
  baselines: Record<DomainId, number>;
  visions: Partial<Record<DomainId, string>>;
  motivation_style: MotivationStyle;
  rhythm: CheckInRhythm;
  daily_minutes: number;
  promise: string | null;
  promise_horizon_months: number;
  timezone: string;
  onboarding_complete: boolean;
  started_at: string;
  created_at: string;
  updated_at: string;
}

export interface AccountRow {
  id: string;
  email: string | null;
  trial_started_at: string;
  trial_days: number;
  status: AccountStatus;
  plan: string | null;
  past_due_since: string | null;
  role: AccountRole;
  bypass_billing: boolean;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  current_period_end: string | null;
  documents_sent_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface QuestRow {
  id: string;
  user_id: string;
  domain: DomainId;
  title: string;
  detail: string | null;
  cadence: Cadence;
  kind: QuestKind;
  difficulty: number;
  time_window: QuestWindow;
  target: number | null;
  unit: string | null;
  source: string;
  created_at: string;
  active_periods: Array<{ startedAt: string; endedAt?: string }> | null;
  archived_at: string | null;
  updated_at: string;
}

export interface LogRow {
  id: string;
  user_id: string;
  quest_id: string;
  day: string;
  status: string;
  value: number | null;
  at: string;
}

export interface GoalRow {
  id: string;
  user_id: string;
  domain: DomainId;
  title: string;
  why: string | null;
  target_date: string | null;
  target: number | null;
  current: number | null;
  unit: string | null;
  source: string;
  created_at: string;
  completed_at: string | null;
  updated_at: string;
}

export interface ReflectionRow {
  user_id: string;
  day: string;
  mood: number | null;
  note: string | null;
  at: string;
}

export interface UnlockedAchievementRow {
  user_id: string;
  achievement_id: string;
  unlocked_at: string;
}

export interface AdminUserOverviewRow {
  id: string;
  email: string | null;
  status: AccountStatus;
  role: AccountRole;
  plan: string | null;
  bypass_billing: boolean;
  trial_started_at: string;
  trial_days: number;
  past_due_since: string | null;
  current_period_end: string | null;
  created_at: string;
  updated_at: string;
  display_name: string | null;
  onboarding_complete: boolean | null;
  quest_count: number;
  log_count: number;
  last_active_day: string | null;
}
